using Frends.JSON.Query.Definitions;
using Frends.JSON.Query.Helpers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Threading;

namespace Frends.JSON.Query;

/// <summary>
/// JSON Task.
/// </summary>
public static class JSON
{
    /// Mem cleanup.
    static JSON()
    {
        var currentAssembly = Assembly.GetExecutingAssembly();
        var currentContext = AssemblyLoadContext.GetLoadContext(currentAssembly);
        if (currentContext != null)
            currentContext.Unloading += OnPluginUnloadingRequested;
    }

    /// <summary>
    /// Query JSON string/token.
    /// [Documentation](https://tasks.frends.com/tasks/frends-tasks/Frends.JSON.Query)
    /// </summary>
    /// <param name="input">Input parameters</param>
    /// <param name="options">Optional parameter.</param>
    /// <param name="cancellationToken">Token generated by frends to stop this Task.</param>
    /// <returns>Object { bool Success, IEnumerable&lt;object&gt; Data, Error Error }</returns>
    public static Result Query([PropertyTab] Input input, [PropertyTab] Options options, CancellationToken cancellationToken)
    {
        try
        {
            cancellationToken.ThrowIfCancellationRequested();
            JToken jToken = GetJTokenFromInput(input.Json);
            var tokens = jToken.SelectTokens(input.Query, options.ErrorWhenNotMatched).ToList();

            if (tokens.Count == 0 && options.ErrorWhenNotMatched)
                throw new JsonException($"No matches found for query '{input.Query}'.");

            return new Result { Success = true, Data = tokens };
        }
        catch (Exception ex)
        {
            return ex.Handle(options);
        }
    }

    private static object GetJTokenFromInput(dynamic json)
    {
        if (json is string)
            return JToken.Parse(json);

        if (json is JToken)
            return json;

        throw new InvalidDataException("The input data was not recognized. Supported formats are JSON string and JToken.");
    }

    private static void OnPluginUnloadingRequested(AssemblyLoadContext obj)
    {
        obj.Unloading -= OnPluginUnloadingRequested;
    }
}