name: Validate build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.JSON.Validate/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.JSON.Validate
    secrets:
      build_time_nuget_feed_url: ${{ secrets.PRIVATE_NUGET_FEED_URL }}
      build_time_nuget_feed_api_key: ${{ secrets.PRIVATE_NUGET_FEED_API_KEY }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}